enabled: true
production-mode: true
grid-size: grid-lg
header-fixed: true
header-animated: true
header-dark: false
header-transparent: false
sticky-footer: true
blog-page: /blog
spectre:
  exp: false
  icons: false
favicon: favicon.ico
logo: logo.png
copyright: "Design and Developed by <a href=\"http://www.Themefisher.com\" target=\"_blank\">Themefisher</a>. <br> \r\nGet More \r\n<a href=\"https://themefisher.com/free-bootstrap-templates/\" target=\"_blank\">Free Bootstrap Templates </a>"
social_icons:
  -
    url: 'http://wwww.fb.com/themefisher'
    classes: Facebook
    icon: ion-social-facebook
  -
    url: 'http://wwww.twitter.com/themefisher'
    classes: Twitter
    icon: ion-social-twitter
  -
    url: '#'
    classes: Linkedin
    icon: ion-social-linkedin
  -
    url: 'http://wwww.fb.com/themefisher'
    classes: 'Google Plus'
    icon: ion-social-googleplus
cta:
  title: 'SO WHAT YOU THINK ?'
  content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis,<br>possimus commodi, fugiat magnam temporibus vero magni recusandae? Dolore, maxime praesentium.'
  button_url: /contact
  button_label: 'Contact With Me'
